# -*- coding: utf-8 -*-
"""phase1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIV6M-oeGc7jdfqk-2wB4bqDVE_32onD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import json
import nltk

# Install required sentiment libraries
# !pip install vaderSentiment textblob -qq

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import warnings
warnings.filterwarnings("ignore")

#1 Load Data from the Json file
file_path ="/content/sample_data/All_Beauty.json"

df = pd.read_json("All_Beauty.json", lines=True)

print("Dataset Shape - ", df.shape)
print(df.head())

# Data Exploration
print("\n\n---------- Data Exploration ----------")
print("\nTotal Reviews - ", len(df))
print("Unique Products - ", df["asin"].nunique())
print("Unique Users - ", df["reviewerID"].nunique())
print("Average Rating - ", df["overall"].mean())

# Distribution of reviews per product
prod_dist = df.groupby('asin').size().describe()

# Rating Distribution
print("\nRating Distribution - ")
print(df["overall"].value_counts())

# Plot rating distribution
plt.figure(figsize=(6,4))
sns.countplot(x="overall", data=df)
plt.title("Rating Distribution")
plt.show()

# Reviews per Product summary
reviews_per_product = df.groupby("asin").size()
print("\nReviews per Product - Summary")
print(reviews_per_product.describe())

# Reviews per User summary
reviews_per_user = df.groupby("reviewerID").size()
print("\nReviews per User - Summary")
print(reviews_per_user.describe())

# Review Length
# Reaplacing missing text with empty strings
df["reviewText"] = df["reviewText"].fillna("")
df["summary"] = df["summary"].fillna("")
df["review_length"] = df["reviewText"].apply(lambda x: len(str(x)))

print("\nReview Length Status - ")
print(df["review_length"].describe())

# Plot review length distribution
plt.figure(figsize=(6,4))
sns.histplot(df["review_length"], bins=50)
plt.title("Review Length Distribution")
plt.show()

# Check duplicates
print("\nDuplicate Rows - ", df.duplicated(subset=['reviewerID', 'asin', 'reviewText', 'overall']).sum())


#2. Pre-processing
print("\n\n---------- Pre-processing ----------")

# Convert rating to sentiment labels
def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

df["sentiment"] = df["overall"].apply(label_sentiment)

print("\nSentiment Distribution - ")
print(df["sentiment"].value_counts())

# Combine summary and review text
df["full_text"] = df["summary"] + " " + df["reviewText"]

# Remove very short reviews
df = df[df["review_length"] > 3]

# Outlier check: Review length
df['review_len'] = df['full_text'].apply(len)
# Filtering out empty reviews or extremely long outliers
df = df[df['review_len'] > 2]


# 4. Sample Data - 1000 reviews
df_sample = df.sample(n=min(1000, len(df)), random_state=77)
print("\nSample Shape - ", df_sample.shape)


# For VADER (minimal cleaning)
def preprocess_vader(text):
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

# For TextBlob (stronger cleaning)
def preprocess_textblob(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df_sample["text_vader"] = df_sample["full_text"].apply(preprocess_vader)
df_sample["text_blob"] = df_sample["full_text"].apply(preprocess_textblob)

# 6. Model 1 - VADER
# Initalize VADER analyzer
analyzer = SentimentIntensityAnalyzer()

def vader_sentiment(text):
    score = analyzer.polarity_scores(text)["compound"]
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

df_sample["vader_pred"] = df_sample["text_vader"].apply(vader_sentiment)


# 7. Model 2 - TEXTBLOB
def textblob_sentiment(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df_sample["textblob_pred"] = df_sample["text_blob"].apply(textblob_sentiment)


# 8. Evalation
print("\n\n---------- Evaluation for both models ----------")
print("\n--- VADER RESULTS ---")
print("Accuracy - ", accuracy_score(df_sample["sentiment"], df_sample["vader_pred"]))
print(classification_report(df_sample["sentiment"], df_sample["vader_pred"]))

print("\n--- TEXTBLOB RESULTS ---")
print("Accuracy - ", accuracy_score(df_sample["sentiment"], df_sample["textblob_pred"]))
print(classification_report(df_sample["sentiment"], df_sample["textblob_pred"]))


# 9. Confusion matrices
# VADER confusion matrix
plt.figure(figsize=(6,4))
cm_vader = confusion_matrix(df_sample["sentiment"], df_sample["vader_pred"], labels=["Positive","Neutral","Negative"])
sns.heatmap(cm_vader, annot=True, fmt="d", xticklabels=["Positive","Neutral","Negative"],
            yticklabels=["Positive","Neutral","Negative"])
plt.title("---------- VADER Confusion Matrix -----------")
plt.show()

# TextBlob confusion matrix
plt.figure(figsize=(6,4))
cm_blob = confusion_matrix(df_sample["sentiment"], df_sample["textblob_pred"], labels=["Positive","Neutral","Negative"])
sns.heatmap(cm_blob, annot=True, fmt="d", xticklabels=["Positive","Neutral","Negative"],
            yticklabels=["Positive","Neutral","Negative"])
plt.title("---------- TextBlob Confusion Matrix -----------")
plt.show()


# 10. Comparsion table
print("\n\n---------- COMPARISON TABLE ----------")
vader_acc = accuracy_score(df_sample["sentiment"], df_sample["vader_pred"])
blob_acc = accuracy_score(df_sample["sentiment"], df_sample["textblob_pred"])

comparison = pd.DataFrame({
    "Model": ["VADER", "TextBlob"],
    "Accuracy": [vader_acc, blob_acc]
})

print("\nModel Comparison - ")
print(comparison)